### ISSUE TITLE
Registration issues

### ISSUE THREAD

**Issue by elliot-forty-two** [platky/PkmnCardsOnline-Frontend#6]
Registering seems to be successful, but I received 2 verification emails at the one time.

The register dialog also doesn't complete and just shows a large spinner. The JS console in Chrome shows an error at view.js:1653
SyntaxError: Unexpected token M
    at Object.parse (native)
    at m.parseJSON (https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:5:15998)
    at Pb (https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:5:18379)
    at x (https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:5:21793)
    at XMLHttpRequest.b (https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:5:26030)

I also noticed that there's debug with the contents of my login attempt (before registering) and my registration that include my password in plain-text. You should be securing the site with an SSL certificate or securing the password some other way before transmitting it unsecured. I also tried to access https://www.pkmncardsonline.com and got a certificate error (self signed?) which is OK, but got to a "Default Web Site Page" landing page. Ideally, the HTTPS address should be properly secured and serving the main site, with the HTTP address performing a redirect (maybe with a 301 Moved) to the HTTPS version to enforce security.

**Comment by elliot-forty-two** [comment]
I also saw some response debug with my password in plain text, big no-no. How are you storing the passwords in your database? Hashed?

**Comment by platky** [comment]
- Registration issue fixed
- Email issue should be fixed, I could not replicate it anymore
- Debug issue fixed, was a remnant from a while ago

- Currently in the process of getting a proper cert and setting up https, will update
- password is hashed +salt, it is not stored in plain text anywhere

**Comment by elliot-forty-two** [comment]
Cool, I thought that'd be the case with the password, I was just suspicious because it came back in a response that it could have been stored like that :)

**Comment by platky** [comment]
Will revisit https in the future, currently pulls images from non-https locations. Will need to set up a proxy as a go between
