### ISSUE TITLE
Unavailable Sets

### ISSUE THREAD

**Issue by aoshiz** [platky/PkmnCardsOnline-Frontend#8]
Can't find the sets:

Double Crisis
http://bulbapedia.bulbagarden.net/wiki/Double_Crisis_%28TCG%29

Kalos Starter Set
http://bulbapedia.bulbagarden.net/wiki/Kalos_Starter_Set_%28TCG%29

**Comment by platky** [comment]
I would consider both of those sub-sets which is why I didn't include them in the main set listing page. They will be a part of the promo section

**Comment by aoshiz** [comment]
Ok. You are the boss.
:)
